### PR TITLE
Changes that should have been synced a year ago

### PR DESCRIPTION
**Pull request by clefourrier**
I'm going to close my version of this repository. 
Apparently your version is way behind compared to the original version; it would appear that your fork was never synced with all the modifs I made a year ago according to the project's specs.

Please update your fork to get the "latest" version of the project.

### CODE REVIEW

**Comment by ludovicc** [comment]
Thanks @clefourrier for the update. This is your code and you have commit rights to this repository, so I assume that it was your responsibility to keep the repositories in sync.

**Comment by clefourrier** [comment]
@ludovicc I don't have write access to this repository, and as such, have not been able to either sync it nor merge my pull request. 
I'm not sure how it could have been my responsibility to sync your fork of my project. I guess it doesn't really matter now though.

**Comment by ludovicc** [comment]
@clefourrier Can you re-open this pull request, because the code was not actually merged. Thanks

**Comment by ludovicc** [comment]
My previous comment did reopen and I was able to merge the code. Thanks again

**Pull request merged**
